a = int(input("A"))
b = int(input("B"))
print("Q1.Floor Division")
print("Floor division is",a//b)
print("Q2.a power b")
print("A Power B is",a**b)
print("Q3.Find out whether two variables have equal value or not- if yes then print True if they are not equal then print False")
print("The statement is",a==b)